import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed-variant": "#69355a",
        "on-primary": "#ffffff",
        "surface-container": "#eeedef",
        "tertiary-fixed": "#ffd7ee",
        "surface-tint": "#6b5582",
        "tertiary-container": "#9c628a",
        tertiary: "#814970",
        "on-primary-fixed-variant": "#533e69",
        "on-primary-container": "#fffbff",
        "surface-dim": "#dadadc",
        surface: "#faf9fb",
        "primary-fixed": "#efdbff",
        "on-error-container": "#93000a",
        "surface-container-highest": "#e3e2e4",
        background: "#faf9fb",
        "primary-fixed-dim": "#d7bcf0",
        "inverse-surface": "#2f3032",
        "primary-container": "#826b9a",
        "surface-variant": "#e3e2e4",
        "on-primary-fixed": "#25113b",
        "surface-bright": "#faf9fb",
        "on-surface-variant": "#4a454d",
        "on-secondary": "#ffffff",
        "secondary-container": "#fad3fd",
        "inverse-primary": "#d7bcf0",
        "on-secondary-container": "#77587c",
        "on-tertiary-fixed": "#36082c",
        primary: "#695380",
        "surface-container-high": "#e8e8ea",
        outline: "#7b757e",
        "inverse-on-surface": "#f1f0f2",
        "on-background": "#1a1c1d",
        "surface-container-low": "#f4f3f5",
        error: "#ba1a1a",
        "error-container": "#ffdad6",
        "tertiary-fixed-dim": "#f6b2de",
        "on-secondary-fixed": "#2a1131",
        "secondary-fixed-dim": "#dfbbe4",
        "surface-container-lowest": "#ffffff",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#fffbff",
        secondary: "#725477",
        "on-surface": "#1a1c1d",
        "on-error": "#ffffff",
        "secondary-fixed": "#fcd7ff",
        "outline-variant": "#ccc4ce",
        "on-secondary-fixed-variant": "#593d5f",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "container-padding-desktop": "64px",
        "section-gap": "80px",
        gutter: "24px",
        "container-padding-mobile": "20px",
        unit: "8px",
      },
      fontFamily: {
        "body-lg": ["Plus Jakarta Sans", "sans-serif"],
        "headline-lg-mobile": ["Plus Jakarta Sans", "sans-serif"],
        "label-sm": ["Plus Jakarta Sans", "sans-serif"],
        "headline-md": ["Plus Jakarta Sans", "sans-serif"],
        "headline-lg": ["Plus Jakarta Sans", "sans-serif"],
        display: ["Plus Jakarta Sans", "sans-serif"],
        "body-md": ["Plus Jakarta Sans", "sans-serif"],
        "label-md": ["Plus Jakarta Sans", "sans-serif"],
      },
      fontSize: {
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-lg-mobile": ["28px", { lineHeight: "1.3", fontWeight: "600" }],
        "label-sm": ["12px", { lineHeight: "1.2", fontWeight: "500" }],
        "headline-md": ["24px", { lineHeight: "1.4", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "1.3", fontWeight: "600" }],
        display: [
          "48px",
          { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-md": [
          "14px",
          { lineHeight: "1.2", letterSpacing: "0.05em", fontWeight: "500" },
        ],
      },
    },
  },
  plugins: [],
};

export default config;
